/**
 * IoT Sensor Simulator Service
 * Generates synthetic IoT sensor readings for hive monitoring demonstration.
 * NOTE: Data generated by this module is purely simulated. No physical IoT hardware is connected.
 */
const generateSimulatedReading = (hive, lastKnownReading = null, forceAnomaly = false) => {
  // 15% probability of generating an anomaly unless forced
  const isAnomaly = forceAnomaly || Math.random() < 0.15;

  let temp;
  if (isAnomaly && Math.random() < 0.5) {
    // High temperature anomaly (37.0 - 41.5 °C)
    temp = Number((37.0 + Math.random() * 4.5).toFixed(1));
  } else if (isAnomaly) {
    // Low temperature anomaly (27.0 - 31.5 °C)
    temp = Number((27.0 + Math.random() * 4.5).toFixed(1));
  } else {
    // Normal temperature range (33.0 - 36.0 °C)
    temp = Number((33.0 + Math.random() * 3.0).toFixed(1));
  }

  let humidity;
  if (isAnomaly && Math.random() < 0.5) {
    // High humidity anomaly (72 - 85 %)
    humidity = Number((72 + Math.random() * 13).toFixed(1));
  } else if (isAnomaly) {
    // Low humidity anomaly (30 - 38 %)
    humidity = Number((30 + Math.random() * 8).toFixed(1));
  } else {
    // Normal humidity range (50 - 70 %)
    humidity = Number((50 + Math.random() * 20).toFixed(1));
  }

  let weight;
  const baseWeight = lastKnownReading && lastKnownReading.weight
    ? Number(lastKnownReading.weight)
    : (hive && hive.weight ? Number(hive.weight) : 35.0);

  if (isAnomaly && Math.random() < 0.4) {
    // Sudden weight drop anomaly (drop of 3.5 - 5.0 kg)
    weight = Number(Math.max(5.0, baseWeight - (3.5 + Math.random() * 1.5)).toFixed(1));
  } else {
    // Normal gradual delta (-0.3 to +0.3 kg)
    const delta = (Math.random() * 0.6) - 0.3;
    weight = Number(Math.max(10.0, Math.min(80.0, baseWeight + delta)).toFixed(1));
  }

  let activity;
  if (isAnomaly) {
    activity = 'LOW';
  } else {
    const actRoll = Math.random();
    if (actRoll < 0.75) {
      activity = 'NORMAL';
    } else if (actRoll < 0.90) {
      activity = 'HIGH';
    } else {
      activity = 'LOW';
    }
  }

  return {
    hive_id: hive ? hive.id : null,
    temp,
    humidity,
    weight,
    activity,
    is_simulated: 1,
    simulated: true,
    data_source: 'SIMULATED SENSOR DATA',
    timestamp: new Date().toISOString()
  };
};

module.exports = {
  generateSimulatedReading
};
